micronaut:
  server:
    port: 8086
  jackson:
    enabled: true

---

aws:
  sqs_test_queue_url: ${``}

---

datasource:
  url:
  username:
  password:
  driverClassName:

---

redisson:
  single-server-config:
    address:
    password:
    database:
  threads: 16
  netty-threads: 32